a= input ('Digite alguma coisa :')
print ('o tipo primitivo desse valor é', type(a))
print ('Só tem espaços ? ', a.isspace())
print ('È um numero ?' , a.isnumeric())
print ('È alfabetico? ', a.isalpha())
print ('È alfanumerico ?' ,a.isalnum())
print ('Está em maiuculas ?', a.isupper())
print ('Está em minusculas ',a.islower())
print ('Está capitalizada ? ',a.istitle())
